services:
  webfrontend:
    build: 
      context: ./src/client/nginx  # Directory containing Dockerfile
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports: 
      - "8082:8082"  # HTTP
      - "8083:8083"  # HTTPS
    depends_on:
      - webapp
    volumes:
      - ./ssl/devcert.crt:/etc/nginx/ssl/devcert.crt:ro
      - ./ssl/devcert.key:/etc/nginx/ssl/devcert.key:ro
    restart: unless-stopped  

  webapp:
    build:
      context: .
      dockerfile: src/WebApp/Dockerfile      
      args:
        BUILD_CONFIGURATION: ${BUILD_CONFIGURATION:-Release}
    image: webapp:${BUILD_CONFIGURATION:-release}
    environment:      
      ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
      ASPNETCORE_URLS: http://+:8080
    ports:
      - "8080:8080" # Http only. Https Requests redirected from reverse proxy      

  db:
    image: postgres:15
    container_name: postgres-db  # Specify the container name
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SupportBot
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
