services:
  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: src/WebApp/Dockerfile
    ports:
    - "8080:8080"
    - "8081:8081"

  db:
    image: postgres:15
    container_name: postgres-db  # Specify the container name
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: yourDatabase
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:latest
    restart: always
    ports:
        -   "6379:6379"

volumes:
  postgres_data: 