services:
  webfrontend:
   image: nginx:alpine  # Use the lightweight Alpine NGINX image
   container_name: nginx-proxy
   ports: 
      - "8080:8080"
      - "8081:8081"
   depends_on:
      - webapp
   volumes:
      - ./src/client/nginx.conf:/etc/nginx/conf.d/default.conf

  webapp:
    #Always build locally rather than pulling from registory
    #image: ${DOCKER_REGISTRY-}webapp
    build:
      context: .
      dockerfile: src/WebApp/Dockerfile
    ports:
     - "8080:8080"
     - "8081:8081"

  db:
    image: postgres:15
    container_name: postgres-db  # Specify the container name
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: SupportBot
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data

  cache:
    image: redis:latest
    restart: always
    ports:
        -   "6379:6379"

volumes:
  postgres_data: 